// Generated by hollowpoint version 0.1.0
import './foreign.dart' as $foreign;
export './foreign.dart';
class Eq1 {
    final dynamic eq1;
    const Eq1(this.eq1);
    static dynamic get create => (eq1) {
        return Eq1(eq1);
    };
}
class Eq {
    final dynamic eq;
    const Eq(this.eq);
    static dynamic get create => (eq) {
        return Eq(eq);
    };
}
final eqVoid = Eq((v) {
    return (v1) {
        return true;
    };
});
final eqUnit = Eq((v) {
    return (v1) {
        return true;
    };
});
final eqString = Eq($foreign.eqStringImpl);
final eqNumber = Eq($foreign.eqNumberImpl);
final eqInt = Eq($foreign.eqIntImpl);
final eqChar = Eq($foreign.eqCharImpl);
final eqBoolean = Eq($foreign.eqBooleanImpl);
eq1(dict) {
    return dict['eq1'];
}
eq(dict) {
    return dict['eq'];
}
eqArray(dictEq) {
    return Eq($foreign.eqArrayImpl(eq(dictEq)));
}
final eq1Array = Eq1((dictEq) {
    return eq(eqArray(dictEq));
});
notEq(dictEq) {
    return (x) {
        return (y) {
            return eq(eqBoolean)(eq(dictEq)(x)(y))(false);
        };
    };
}
notEq1(dictEq1) {
    return (dictEq) {
        return (x) {
            return (y) {
                return eq(eqBoolean)(eq1(dictEq1)(dictEq)(x)(y))(false);
            };
        };
    };
}
