// Generated by hollowpoint version 0.1.0
import 'package:pkg/control/semigroupoid/index.dart' as Control_Semigroupoid;
class Category {
    final dynamic Semigroupoid0;
    final dynamic identity;
    const Category(this.Semigroupoid0, this.identity);
    static dynamic get create => (Semigroupoid0) {
        return (identity) {
            return Category(Semigroupoid0, identity);
        };
    };
}
identity(dict) {
    return dict['identity'];
}
final categoryFn = Category(() {
    return Control_Semigroupoid.semigroupoidFn;
}, (x) {
    return x;
});
