// Generated by hollowpoint version 0.1.0
import './foreign.dart' as $foreign;
export './foreign.dart';
import 'package:pkg/data/unit/index.dart' as Data_Unit;
import 'package:pkg/data/void/index.dart' as Data_Void;
class Semigroup {
    final dynamic append;
    const Semigroup(this.append);
    static dynamic get create => (append) {
        return Semigroup(append);
    };
}
final semigroupVoid = Semigroup((v) {
    return Data_Void.absurd;
});
final semigroupUnit = Semigroup((v) {
    return (v1) {
        return Data_Unit.unit;
    };
});
final semigroupString = Semigroup($foreign.concatString);
final semigroupArray = Semigroup($foreign.concatArray);
append(dict) {
    return dict['append'];
}
semigroupFn(dictSemigroup) {
    return Semigroup((f) {
        return (g) {
            return (x) {
                return append(dictSemigroup)(f(x))(g(x));
            };
        };
    });
}
