// Generated by hollowpoint version 0.1.0
import 'package:pkg/data/show/index.dart' as Data_Show;
Void(x) {
    return x;
}
absurd(a) {
    return (() {
        spin(v) {
            return (() {
                final $1 = v;
                final b = $1;
                return spin(b);
            })();
        }
        return spin(a);
    })();
}
final showVoid = Data_Show.Show(absurd);
