// Generated by hollowpoint version 0.1.0
class Semigroupoid {
    final dynamic compose;
    const Semigroupoid(this.compose);
    static dynamic get create => (compose) {
        return Semigroupoid(compose);
    };
}
final semigroupoidFn = Semigroupoid((f) {
    return (g) {
        return (x) {
            return f(g(x));
        };
    };
});
compose(dict) {
    return dict['compose'];
}
composeFlipped(dictSemigroupoid) {
    return (f) {
        return (g) {
            return compose(dictSemigroupoid)(g)(f);
        };
    };
}
