// Generated by hollowpoint version 0.1.0
import './foreign.dart' as $foreign;
export './foreign.dart';
import 'package:pkg/data/show/index.dart' as Data_Show;
final showUnit = Data_Show.Show((v) {
    return "unit";
});
