// Generated by hollowpoint version 0.1.0
import './foreign.dart' as $foreign;
export './foreign.dart';
class Show {
    final dynamic show;
    const Show(this.show);
    static dynamic get create => (show) {
        return Show(show);
    };
}
final showString = Show($foreign.showStringImpl);
final showNumber = Show($foreign.showNumberImpl);
final showInt = Show($foreign.showIntImpl);
final showChar = Show($foreign.showCharImpl);
final showBoolean = Show((v) {
    return (() {
        final $2 = v;
        if ($2) {
            return "true";
        };
        if (!$2) {
            return "false";
        };
        throw FallThroughError();
    })();
});
show(dict) {
    return dict['show'];
}
showArray(dictShow) {
    return Show($foreign.showArrayImpl(show(dictShow)));
}
