// Generated by hollowpoint version 0.1.0
import './foreign.dart' as $foreign;
export './foreign.dart';
import 'package:pkg/data/unit/index.dart' as Data_Unit;
class Semiring {
    final dynamic add;
    final dynamic mul;
    final dynamic one;
    final dynamic zero;
    const Semiring(this.add, this.mul, this.one, this.zero);
    static dynamic get create => (add) {
        return (mul) {
            return (one) {
                return (zero) {
                    return Semiring(add, mul, one, zero);
                };
            };
        };
    };
}
zero(dict) {
    return dict['zero'];
}
final semiringUnit = Semiring((v) {
    return (v1) {
        return Data_Unit.unit;
    };
}, (v) {
    return (v1) {
        return Data_Unit.unit;
    };
}, Data_Unit.unit, Data_Unit.unit);
final semiringNumber = Semiring($foreign.numAdd, $foreign.numMul, 1.0, 0.0);
final semiringInt = Semiring($foreign.intAdd, $foreign.intMul, 1, 0);
one(dict) {
    return dict['one'];
}
mul(dict) {
    return dict['mul'];
}
add(dict) {
    return dict['add'];
}
semiringFn(dictSemiring) {
    return Semiring((f) {
        return (g) {
            return (x) {
                return add(dictSemiring)(f(x))(g(x));
            };
        };
    }, (f) {
        return (g) {
            return (x) {
                return mul(dictSemiring)(f(x))(g(x));
            };
        };
    }, (v) {
        return one(dictSemiring);
    }, (v) {
        return zero(dictSemiring);
    });
}
