// Generated by hollowpoint version 0.1.0
import 'package:pkg/data/eq/index.dart' as Data_Eq;
import 'package:pkg/data/semigroup/index.dart' as Data_Semigroup;
import 'package:pkg/data/show/index.dart' as Data_Show;
class LT {
    const LT();
}
class GT {
    const GT();
}
class EQ {
    const EQ();
}
final showOrdering = Data_Show.Show((v) {
    return (() {
        final $6 = v;
        if ($6 is LT) {
            return "LT";
        };
        if ($6 is GT) {
            return "GT";
        };
        if ($6 is EQ) {
            return "EQ";
        };
        throw FallThroughError();
    })();
});
final semigroupOrdering = Data_Semigroup.Semigroup((v) {
    return (v1) {
        return (() {
            final $7 = v;
            final $8 = v1;
            if ($7 is LT) {
                return LT();
            };
            if ($7 is GT) {
                return GT();
            };
            if ($7 is EQ) {
                final y = $8;
                return y;
            };
            throw FallThroughError();
        })();
    };
});
invert(v) {
    return (() {
        final $9 = v;
        if ($9 is GT) {
            return LT();
        };
        if ($9 is EQ) {
            return EQ();
        };
        if ($9 is LT) {
            return GT();
        };
        throw FallThroughError();
    })();
}
final eqOrdering = Data_Eq.Eq((v) {
    return (v1) {
        return (() {
            final $10 = v;
            final $11 = v1;
            if ($10 is LT) {
                if ($11 is LT) {
                    return true;
                };
            };
            if ($10 is GT) {
                if ($11 is GT) {
                    return true;
                };
            };
            if ($10 is EQ) {
                if ($11 is EQ) {
                    return true;
                };
            };
            return false;
        })();
    };
});
